services:
  postgres:
    image: postgres:15
    container_name: elt_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "55432:5432"
    volumes:
      - data-pipeline-test_pgdata:/var/lib/postgresql/data

volumes:
  data-pipeline-test_pgdata:
